### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by divmain** [divmain/interlock#1]

**Comment by divmain** [comment]
Pinging @baer

**Comment by baer** [comment]
On it! I'll have a look tomorrow - very excited.

**Comment by baer** [comment]
Your package.json points to `/lib/index.js` which is missing btw.

**Comment by divmain** [comment]
:)  Yeah, not complete, but getting closer.  Looking for feedback on API as well as cogency of patterns used, etc.  I started working on this from both ends - the example to flesh out the API, and the deepest modules outward - so that's what's committed so far.  I have a placeholder `index.js` in my working directory but it isn't worth committing yet.
